### ISSUE TITLE
Use 'required' for args

### ISSUE THREAD

**Issue by helfer** [DxCx/webpack-apollo-server#5]
This looks pretty neat, nice job!

Just one little thing I noticed while looking at the schema: Instead of checking the presence of an argument in the resolver, you can specify `username` and `password` as required fields in the GraphQL schema. That way GraphQL will check it for you during validation: https://github.com/DxCx/webpack-apollo-server/blob/bc520808d1bb2009700f56f71b86634ebe182c42/src/schema.ts#L44

**Comment by DxCx** [comment]
Done,
required: True does not work,
however, if i wrap the type with GraphQLNonNull, it makes it required in schema
